### ISSUE TITLE
Genre toggles on the profile not working

### ISSUE THREAD

**Issue by k-lamby** [AgileCrocodile/bibliophile#10]
The final toggle is persisting despite not being written into the database:

![image](https://user-images.githubusercontent.com/58035625/131110768-2e804a13-32ec-4bca-9068-073d081a7fed.png)
![image](https://user-images.githubusercontent.com/58035625/131110788-e00c0c44-3c72-4443-b7ab-65c3f8928fb9.png)

**Comment by holyjc827** [comment]
It works fine at the moment.
