### ISSUE TITLE
Clearer instructions needed

### ISSUE THREAD

**Issue by hannes-seller** [AgileCrocodile/bibliophile#21]
Matchmaking:
- Some users think the thumbs are for ratings
- It would be clearer to have the page named: "Get a recommendation", as some users think the "add a book" will send it to the wishlist, while other users think the wishlist is used to expand the wishlist. (If you change the word, please look at other pages as well where "Matchmaking" is mentioned!)
- Should give instruction "Give the book a thumbs up to add it to your personal wishlist. Give it a thumbs down to ignore it."

Wishlist:
- Should give instruction: "The wishlist shows the books that you want to get to know better. Go to <either "Matchmaking" or "Get a recommendation"> to add more books to your wishlist."
- Change "mark as read" into "Teach a one liner" or "Add a one liner". (Please pay attention to consistent spelling of "one liner"!)

Add a book:
- Add "The books you add to the database will be recommended to other users. Please don't register books that might be inappropriate offensive to other users."

Profile / Settings
- Add "Which genres would you like to see in the recommendations? Confirm your selection with the 'Update' button."

**Comment by k-lamby** [comment]
Added the additional comments
