### ISSUE TITLE
Top menu bar overhaul and accessibility

### ISSUE THREAD

**Issue by hannes-seller** [AgileCrocodile/bibliophile#23]
(1) Almost all testers find the font too small. (Might be due to image I uploaded, but there is nonetheless 75% of the bar empty).

(2) The heart logo needs a margin to the left to not touch the window frame.

(3) There should be some padding between the heart and the application name

(4) Settings and Register Now could be aligned to the right, to better cluster the functions.

(5) Currently active tab could be highlighted.

(5) If you do an overhaul: I would prefer these tabs in the following order with clearer tabs (a calls to action):
<3 "Bibliophile"            "Get recommendations" (matchmaking)    "My wishlist"      "Recommend a book" (add a book)
                                                                                   (some space)                                                  "Settings"           "Login"

**Comment by k-lamby** [comment]
(1) Increase the link font size, not increased the overall depth of the bar as it is quite big already (see screenshot).

(2) Margin added to heart logo

(3) Added

(4) Now aligned to the right

(5) Added logic to highlight navbar

(6) Changed around

![image](https://user-images.githubusercontent.com/58035625/131558780-d8888a49-663e-4113-84ab-a899417bc40b.png)
